### PR TITLE
Update MultiMeter

### PR DESCRIPTION
**Pull request by RealAlexZ**
Hi,

I hope that you are doing well! I am hoping to add my recently completed open-sourced plugin, MultiMeter, to your repository. I immensely appreciate your consideration, and thank you for compiling this wonderful list!

Best,
Alex

### CODE REVIEW

**Comment by webprofusion-chrisc** [comment]
Hi Alex, thanks for your contribution and for sharing your nice plugin. To add to our list edit the respective json file and our build system will do the rest, I think you need to edit this one: https://github.com/webprofusion/OpenAudio/blob/master/data/plugins.json

**Comment by webprofusion-chrisc** [comment]
To encourage adoption of your plugin I'd also suggest having a website for users to download the prebuilt plugin, or use github releases (or github pages etc) as only a very tiny part of your audience can build from source.

**Comment by RealAlexZ** [comment]
Hi Christopher,

Thank you very much for pointing out the unnecessary changes in my previous commit - I have reverted it and modified the plugins json file for your review. I will also create a GitHub release soon. Thanks again for your great advice!

Sincerely,
Alex

**Comment by RealAlexZ** [comment]
Hi Christopher,

I hope that you are doing well! I just saw that the generation was not successful - is there any possibility that you have any idea of why that is the case? Thanks in advance, and I'm looking forward to hearing back from you!

Sincerely,
Alex

**Comment by webprofusion-chrisc** [comment]
@RealAlexZ ah thanks it's just failing on the test to check the entries are in alphabetical order, if you move yours down to M that should fix it.

**Comment by RealAlexZ** [comment]
Hello Christopher,

I hope that you are doing well! I am very sorry for the late reply - I somehow got terribly sick last week and was not able to get back to you on time. I have now checked that the json file is in the right alphabetical order, and I would really appreciate if there is any chance that you can generate the README again! Thanks in advance, and I am looking forward to hearing back from you soon.

Sincerely,
Alex

**Comment by webprofusion-chrisc** [comment]
Thanks Alex, that's all merged and published now, much appreciated.

**Pull request merged**
