### PR TITLE
README Generation

### PR DESCRIPTION
**Pull request by satelllte**
## About

Automated `README.md` generation from Node.js project with data sources.

## What's included

- Node.js `./generator` project, which generates `README.md` file from its data sources
- Data sources are decoupled, which means that they're better machine readable now and can be used for other things potentially (e.g., for HTML page generation instead of Markdown)
- 100% typed with TypeScript
- Tests for:
  - Markdown renderers
  - Data sources sorting
  - Code linting with ESLint
  - Code formatting with Prettier
- GitHub Actions CI which commits with updated `README.md` if all tests passed
- VSCode settings for easier workflow with TypeScript, ESLint and Prettier

## Please note

Most `README.md` file difference appeared due to sorting. If it's inconvenient to review it, the sorting tests could be disabled for this PR, so the sorting change can be made later separately.

### CODE REVIEW

**Comment by webprofusion-chrisc** [comment]
Wow! Thanks, wasn't expecting this. This is basically a fix for #16 to some extent.

Will review this shortly.

**Comment by webprofusion-chrisc** [comment]
Thanks, I'm going to merge this and then see what tweaks might be made. I'll write a contributions guide to help non-developers contribute changes to the lists, and maybe re-arrange the directory structure just a little so that data isn't mixed with code/tests. It think there is scope to also format the generated results as a JSON "static API" so others can pull the list. Long term we probably need a way to link to plugin downloads directly but that's platform dependant - e.g. if you could open a DAW, open a list of plugins (from this data) and click to download and install.

**Comment by satelllte** [comment]
> I think there is scope to also format the generated results as a JSON "static API" so others can pull the list. Long term we probably need a way to link to plugin downloads directly but that's platform dependant - e.g. if you could open a DAW, open a list of plugins (from this data) and click to download and install.

This is a good idea. I hope my change is helpful for this. JSON "static API" can obviously be generated along with the README file, as well as the new field like "platforms" could be introduced.

**Comment by webprofusion-chrisc** [comment]
@Marat-Tanalin I don't totally disagree, but an advantage of typescript is that if an edit fails to include a required property it will fail to build. That could be achieved with Json schema or a data validation test though.

Having a field be either a single value or an array is a little odd though, yes it can be done but it doesn't smell right. I understand the point of view that it makes contribution a little more difficult but we could consider a form people can fill out for submissions instead of via GitHub edits.

This is just a first stage, I'm sure we'll progress from here.

**Comment by Marat-Tanalin** [comment]
JSON is a standard format supported by multiple languages as is. Using TS effectively disallows alternative non-TS implementations, e.g. my server-side language is PHP. Also, mixing irrelevant program code with data is error-prone when editing, especially by a nonprogrammer.

Accepting both an array and a single value is quite an established practice used e.g. in Zend Framework (now Laminas). In scripting languages such as JS, TS, or PHP, this is as simple as automatically wrapping the variable in an array if it’s not an array already. In terms of value-format consistency when committing added/removed lines in VCS/SCM, the framework list is not supposed to change any frequently because it’s usually basically constant for absolute majority of software, so once written for an item (instrument, app, etc.), the field keeps the original value basically forever.

Sure, I see this is the first stage, just trying to make sure you are aware of some important aspects, as soon as possible.

**Comment by webprofusion-chrisc** [comment]
@Marat-Tanalin thanks, it's very likely we'll move to JSON but I'd even like to consider having one JSON doc per item so that changes are more fine-grained. I already added a JSON export step with the idea that it will export JSON for a static API.

There are things I would have done differently (I'd probably use a pre-built generator like 11ty instead of scripting one, and I'd use JSON for the data) but this solution came out of nowhere, didn't require me to do all the work, was a working solution with tests and generated a README that's almost identical to the manually created one.

**Comment by satelllte** [comment]
@webprofusion-chrisc If you'll move the data source to JSON, my suggestion would be to use [Zod](https://zod.dev/) for type checking, so this way it'll make sure the JSON data aligned with the expected type.

**Comment by webprofusion-chrisc** [comment]
@satelllte thanks, that looks useful.

**Pull request merged**
